spring:
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    initialization-mode: never

com.assignment.spring.weather-client.url: http://api.openweathermap.org/data/2.5/weather?q={city}&APPID=${API_KEY}