spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

com.assignment.spring.weather-client.url: http:localhost:9090/api/weather?q={city}&/APPID=1234